name: Bytedeco
description: Bytedeco, Native kütüphaneleri <strong>JavaCPP</strong> teknolojisi kullanarak Java platformu için kullanılabilir hale getirir. Umarız ki bu çalışmalar Java ve C/C ++ arasındaki kayıp köprüdür.
url: http://bytedeco.org
markdown: kramdown
gems: [jekyll-paginate]
highlighter: rouge
paginate: 1
permalink: /news/:year/:month/:day/:title/